version: "2.0"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
      - 1434:1434
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: n5o_ADMIN
    logging:
      driver: json-file
    network_mode: bridge




